### ISSUE TITLE
Breakdown Epics into smaller issues

### ISSUE THREAD

**Issue by georgeslabreche** [georgeslabreche/opssat-orbitai#20]
The Epics:
- [Generalize OrbitAI](https://github.com/georgeslabreche/opssat-orbitai/issues/18)
- [Evaluate the ranger library for batch training with Random Forest](https://github.com/georgeslabreche/opssat-orbitai/issues/19)

Load the issues into the GitHub Projects board so that they can be tracked:
https://github.com/georgeslabreche/opssat-orbitai/projects/2

**Comment by TanguySoto** [comment]
@georgeslabreche @Evridiki-ase please review.

**Comment by georgeslabreche** [comment]
@TanguySoto this looks OK on my end.

**Comment by georgeslabreche** [comment]
I've broken down the epics further.
