### ISSUE TITLE
Compile ranger for ARM and check it runs on flatsat

### ISSUE THREAD

**Issue by TanguySoto** [georgeslabreche/opssat-orbitai#23]
This story is part of epic [Evaluate the ranger library for batch training with Random Forest](https://github.com/georgeslabreche/opssat-orbitai/issues/19).

- investigate how to cross-compile for ARM (mostly likely in the same way we cross-compiled MochiMochi)
- run the ARM binary on the flatsat (@TanguySoto and @georgeslabreche can help with this)

**Comment by georgeslabreche** [comment]
I think @TanguySoto is already super busy as it is and should focus on the NMF app so I volunteer to help @Evridiki-ase instead. @TanguySoto if you agree then please re-assign.

**Comment by georgeslabreche** [comment]
@TanguySoto do you have time to quickly check? I have flatsat SEPP access issues at the moment. Compile and usage instructions are [here](https://github.com/georgeslabreche/opssat-orbitai/tree/main/RandomForest). Specifically, you should run:

```bash
./OrbitAI_ranger --verbose --file test_data/training_data.csv --includevars PD1,PD2,PD3,PD4,PD5,PD6,LABEL --depvarname LABEL --treetype 1 --ntree 10 --write
./OrbitAI_ranger --verbose --includevars PD1,PD2,PD3,PD4,PD5,PD6,LABEL --file test_data/test_data.csv --predict ranger_out.forest
```

**Comment by TanguySoto** [comment]
I'll try this today on the small flatsat!

**Comment by TanguySoto** [comment]
When compiling for ARM I'm getting tons of notes like this:
`parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<double*, std::vector<double> >’ changed in GCC 7.1`
When trying to start it on the flatsat I get an error regarding libm that seems to be of the wrong version (still unsure what this means exactly):
`./OrbitAI_ranger: /lib/libm.so.6: version 'GLIBC_2.29' not found (required by ./OrbitAI_ranger`

**Comment by georgeslabreche** [comment]
@TanguySoto thanks for looking into it. I will investigate further.

**Comment by georgeslabreche** [comment]
@TanguySoto I can run the training on the flatsat:
```bash
./OrbitAI_ranger --verbose --includevars PD1,PD2,PD3,PD4,PD5,PD6,LABEL --file test_data/training_data.csv --depvarname LABEL --treetype 1 --ntree 10 --write
```

But get  a segmentation fault for the prediction:
```bash
root@sepp:~/georges/orbitai# ./OrbitAI_ranger --verbose --includevars PD1,PD2,PD3,PD4,PD5,PD6,LABEL --file test_data/test_data.csv --predict ranger_out.forest
Starting Ranger.
Segmentation fault (core dumped)
```

Has your local dev environment changed in anyway regarding compiling for arm?

**Comment by georgeslabreche** [comment]
@TanguySoto saving and loading the model is messed up: https://github.com/imbs-hl/ranger/issues/566

**Comment by georgeslabreche** [comment]
This has been resolved: https://github.com/imbs-hl/ranger/pull/570
