### ISSUE TITLE
Calculate ranger performances (resources usage on flatsat, accuracy ...)

### ISSUE THREAD

**Issue by TanguySoto** [georgeslabreche/opssat-orbitai#24]
This story is part of epic [Evaluate the ranger library for batch training with Random Forest](https://github.com/georgeslabreche/opssat-orbitai/issues/19).

- Benchmark ranger on the flatsat with realistic amount of data (PD values + labels, maybe 1000 samples minimum?)
- Calculate the classification metrics of the trained model by using the same dataset used in the paper when evaluating the performance of the Mochi models

**Comment by georgeslabreche** [comment]
@Evridiki-ase I'm closing this story in favor of splitting it into two stories instead:
- [Benchmark ranger on the flatsat with realistic amount of data](https://github.com/georgeslabreche/opssat-orbitai/issues/32)
- [Calculate the classification metrics obtained with ranger's Random Forest model by using the same dataset used in the paper](https://github.com/georgeslabreche/opssat-orbitai/issues/33)
