### ISSUE TITLE
Define an interface for experimenters to provide final inputs data with a label

### ISSUE THREAD

**Issue by TanguySoto** [georgeslabreche/opssat-orbitai#27]
This story is part of epic [Generalize OrbitAI](https://github.com/georgeslabreche/opssat-orbitai/issues/18).

- give raw OBSW data to experimenters
- allow experimenters to perform any checks and transformation they want on raw OBSW data
- allow experimenters to give back transformed OBSW data + associated label
- make it easy in case we want to allow non-binary classification

**Comment by georgeslabreche** [comment]
@TanguySoto some note regarding the refactored ML Server:
1. You no longer need to send it a "train" or "infer" string as part of the command string. It will figure this out on its won based on what mode is set the in properties file.
2. When sending data input for training or inference, the first four characters is the command string with the length of the command message, e.g.: 
```
0041 +1 1:1.232 2:2.412 3:2.123 4:5.23223
0031 -1 1:1.232 2:2.412 3:2.123
```

This is described [here](https://github.com/georgeslabreche/opssat-orbitai/blob/ec63201e707bb23bb8ecd35e14cf951a4f27e231/Mochi/src/OrbitAI_Mochi.cpp#L175-L195) but eventually should be documented in the README.

**Comment by georgeslabreche** [comment]
@TanguySoto what do we need to do to get this issue closed?
