### ISSUE TITLE
Refactor C++ ML server

### ISSUE THREAD

**Issue by TanguySoto** [georgeslabreche/opssat-orbitai#28]
This story is part of epic [Generalize OrbitAI](https://github.com/georgeslabreche/opssat-orbitai/issues/18).

The C++ ML server needs a refactor, it is just a giant loop at the moment.

**Comment by georgeslabreche** [comment]
Two design updates:
1. I will load the .properties file from the C++ ML Server app.
2. I will instantiate the ML classes using the [Factory Design Pattern](https://refactoring.guru/design-patterns/factory-method/cpp/example)
